<a href="https://colab.research.google.com/github/Miltontn7677/datasharing/blob/master/C1_M3_Numpy_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy!

This section is all about the package, Numpy. Are you ready? Let's go!

You will find some small tasks in sections below. Most codes are hidden and you can only see the output.

> Try to figure out by yourself, or search for references. Being able to search and find information needed is an important skill that benefits you and your career for a long time.





## Import the package and rename it as np

In [3]:
# your code is here
import numpy as np

## Array Creation

In [ ]:
ar1 = np.array

### Task: Create a numpy array from a list of integers

In [ ]:
# your code is here
ar1 = np.array(range(1, 11))


### Task: Create a numpy array of size 6, filled with zeros

In [ ]:
# your code is here
ar2 = np.zeros(6)

### Task: Create a numpy array of size 6, filled with ones

In [ ]:
# your code is here
ar3 = np.ones(6)

### Task: Create a numpy array with values from 0 to 10

In [ ]:
# your code is here
ar4=np.arange(11)

### Task: Create a numpy matrix of 2*3 integers, filled with zeros

In [ ]:
# your code is here
ar5=np.zeros((2,3))
ar5

array([[0., 0., 0.],
       [0., 0., 0.]])

### Task: Create a numpy matrix of 3*2 integers, filled with ones

In [ ]:
# your code is here
ar6=np.ones((3,2))
ar6

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### Task: Create a numpy matrix of 3*2 integers, filled with random integers in [0, 10]

In [ ]:
# your code is here
ar7=np.random.randint(0,10,(3,2))
ar7

array([[8, 4],
       [7, 8],
       [5, 2]])

### Task: Create a numpy matrix of 100 * 2, filled with random float value in [0, 1]

In [ ]:
# your code is here
ar8=np.random.rand(100,2)

### Task: Create a numpy matrix of 2\*3\*4, filled with integers from 1 to 24.

In [4]:
# your code is here
ar9 = np.arange(1,25).reshape(2,3,4)
ar9


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

## Array Indexing

### Task: Let X be a numpy array, and X = np.array([1, 2, 3, 4, 5])

In [5]:
# your code is here

### Task: Show the first element of X

In [6]:
# your code is here

### Task: Show the last element of X

In [7]:
# your code is here

### Task: Show the first 3 elements of X

In [8]:
# your code is here

### Task: Show the last 3 elements of X

In [9]:
# your code is here

### Task: Show the elements of X whose index is odd (1, 3, 5, ...)

In [10]:
# your code is here

### Task: Show the elements of X except the last one

In [11]:
# your code is here

### Task: Let X be a numpy matrix with dimension 3 * 4, and filled from 0 to 11.

In [12]:
# your code is here

### Task: Show the first row of X

In [13]:
# your code is here

### Task: Show the first column of X

In [14]:
# your code is here

### Task: Show the first element of the first row of X

In [15]:
# your code is here

### Task: Show the last row of X

In [16]:
# your code is here

### Task: Show the last column of X

In [17]:
# your code is here

### Task: Show the last element of the last row of X

In [18]:
# your code is here

### Task: Show all the rows except the last row of X

In [19]:
# your code is here

### Task: Show all the columns except the last column of X

In [20]:
# your code is here

### Task: Show the first two elements of the first two rows

In [21]:
# your code is here

## Array Statistics

### Task: Create a numpy array X, print the sum, mean, std, var, max, min of it

In [22]:
# your code is here

### Task: Create a numpy matrix X as n * m, print the sum, mean, std, var, max, min of the 1st row of it.

In [23]:
# your code is here

### Task: Create a numpy matrix X as n * m, print the sum, mean, std, var, max, min of the 1st column of it.

In [24]:
# your code is here

## Array Linear Algebra

### Task: Create two numpy matrix X with 2 * 2, and Y with 2 * 2. Practice Linear Algebra operations, such as +, -, *, .T, @, etc.

In [25]:
# your code is here
X = np.array([[1, 2], [3, 4]])
Y = np.array([[5, 6], [7, 8]])
print(X + Y)
print(X - Y)
print(X * Y)
print(X.T)
print(X @ Y)


[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[1 3]
 [2 4]]
[[19 22]
 [43 50]]
